/* eslint-disable */
// GENERATED by scripts/process-images.mjs — do not edit by hand.
// Alt text is written in src/data/projects/*.ts, never here.
// 29 images across 6 folders.

import type { ImageAsset } from '@/types/project';

/** Sources narrower than 1600px; `full` is capped at true width. Re-supply. */
export const LOW_RES: readonly string[] = [
  "flats/flat-01 (1441 × 1121 px)",
  "hero/hero-01 (1024 × 768 px)",
  "hero/hero-02 (1024 × 768 px)",
  "interior/interior-11 (1441 × 1120 px)",
  "interior/interior-12 (1441 × 1121 px)",
  "interior/interior-13 (1440 × 1121 px)",
  "offices/office-01 (1441 × 1121 px)",
  "offices/office-02 (1441 × 1121 px)",
  "services/bedroom-01 (1440 × 1121 px)",
  "services/dining-01 (1440 × 1120 px)",
  "services/living-01 (1440 × 1121 px)",
  "services/meeting-01 (1441 × 1121 px)",
  "services/villa-01 (1441 × 1121 px)"
];

export const generatedImages: Record<string, ImageAsset[]> = {
  'architecture': [
    {
      id: 'architecture/architecture-01',
      src: { full: '/img/architecture/architecture-01-full.jpg', card: '/img/architecture/architecture-01-card.jpg', thumb: '/img/architecture/architecture-01-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-01-full.webp', card: '/img/architecture/architecture-01-card.webp', thumb: '/img/architecture/architecture-01-thumb.webp' },
      width: 1600,
      height: 1660,
      lqip: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwBACdASoUABUAPxGAuFWsKCUjKAgBgCIJQBb3AjB2E6BxoBj38fetsmLQ4FT41QAA/tQSw8PhfXXhUa5IMgCfIoeaGvFUbK5j2JuJ8iSGAYBNlnbja1MeccOvdRs+SgsiIbc0zZH3cmG3Iosk8hE6mpxpfTIm8VL1i0M/BDjZrrKkS+PMQVdBbTm8aD65ju8s917whw4NAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'architecture/architecture-02',
      src: { full: '/img/architecture/architecture-02-full.jpg', card: '/img/architecture/architecture-02-card.jpg', thumb: '/img/architecture/architecture-02-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-02-full.webp', card: '/img/architecture/architecture-02-card.webp', thumb: '/img/architecture/architecture-02-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAwBQCdASoUAB4APxF4slIsJySisBgIAYAiCUAWHYWZ/7hvvrF0zPWOXgaCApWKXElW8AD+l/fLkgj2S6xk00rtpoi5yE4MrXUg2yCqrvH0l2lsWIbKlDOZD9HT3S/kGPS9DfVvka7An4RqfgZu+x/5Vwpcs3QW8nu/CDy1G/DfkkZ/4+GYRaY396JvsQhOploSwoXNzhVeYGqDFr9IXReE2PkPwrc4k1dT3fhJgmzlImJJHUb+4AAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'architecture/architecture-03',
      src: { full: '/img/architecture/architecture-03-full.jpg', card: '/img/architecture/architecture-03-card.jpg', thumb: '/img/architecture/architecture-03-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-03-full.webp', card: '/img/architecture/architecture-03-card.webp', thumb: '/img/architecture/architecture-03-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABwBQCdASoUAB4APxF6slQsJ6QjKAqpgCIJYgCw7Azqkv4+xZXYu0CecUzILkeSxF0W/GEAAOJ9XxPYbsstprPqft0YVykkN17k81kThAD1m3mYSdHIAjpgHCXCAIGizCEOjY0LgYbvWGT6kyrIS6+ouARtHSIJ+iSXT+vdkwUh/FW6iQnJspxiZ2AxJ56ETsrx6sv7QHzhAgQV+nBNnf2D5njuy/ToETKksEd3lsZxxHXAAAA=',
      alt: '', // TODO: write alt
    },
  ],
  'flats': [
    {
      id: 'flats/flat-01',
      src: { full: '/img/flats/flat-01-full.jpg', card: '/img/flats/flat-01-card.jpg', thumb: '/img/flats/flat-01-thumb.jpg' },
      webp: { full: '/img/flats/flat-01-full.webp', card: '/img/flats/flat-01-card.webp', thumb: '/img/flats/flat-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQAwCdASoUABAAPxFysFAsJqSisAgBgCIJQAAKohFBgGMLUyIAAP3STbqoAkanZFPj+wL6Q58tAdKFk0O5NW6ms6Szm1pVD7lGFvjbgMmsexRRgDl9GzbSoV6ztVgbTj5pinAJJ6p/oSz0k3iOYfQ9ER9WUVAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-02',
      src: { full: '/img/flats/flat-02-full.jpg', card: '/img/flats/flat-02-card.jpg', thumb: '/img/flats/flat-02-thumb.jpg' },
      webp: { full: '/img/flats/flat-02-full.webp', card: '/img/flats/flat-02-card.webp', thumb: '/img/flats/flat-02-thumb.webp' },
      width: 1600,
      height: 1660,
      lqip: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwBACdASoUABUAPxGAt1WsJ6UjKAgBgCIJQBb3AbyWNTosT276GzYqvu2kI+cDBwAA/tQ2WglrFtoM8CkD/hLpBhQgXFPKxgrX0uWLqfyjlmLbD31qMuBZ1GxlHMjO8UQocUqyruJOfIU75lSHAtnuXTsDwtfk+iO9fSF+Dq3n4PLhH88I9ncAqwzRDE9evqsrN5RRhinKpgAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-03',
      src: { full: '/img/flats/flat-03-full.jpg', card: '/img/flats/flat-03-card.jpg', thumb: '/img/flats/flat-03-thumb.jpg' },
      webp: { full: '/img/flats/flat-03-full.webp', card: '/img/flats/flat-03-card.webp', thumb: '/img/flats/flat-03-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAACQBQCdASoUAB4APxF6sFMsJ6QiqA1RgCIJYgCdAAzqkwc592PupIu6ZiNaPRfLbvH8bPSRUADid1nirJ2T5stx41AhW9LPMDq5tYjSYAb6XQU9yRUiqy3QLiru4EyGiywSuujY2geobCdHZG+GY9NvSxZhaJlFbHtHlHbzpUXLv4DJTsM/1WJcbyyrKDHn+yeiDCFbkzf6v/xxHG2fyHHxdfhkZ6KP6viYqwxoYJSMKuv2YAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-04',
      src: { full: '/img/flats/flat-04-full.jpg', card: '/img/flats/flat-04-card.jpg', thumb: '/img/flats/flat-04-thumb.jpg' },
      webp: { full: '/img/flats/flat-04-full.webp', card: '/img/flats/flat-04-card.webp', thumb: '/img/flats/flat-04-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAAAwBQCdASoUAB4APxF4slIsJySisBgIAYAiCUAWHYWZ3/JlTokOfQ/c23QqzEy5zMX4IAD+l/fLkgj2S6whGXEnJ+ZVfxuaPC1e940Dqe0Z5rv+4jwU8/ccC7Nteqlm+m/REiL+YQiTpR03vqiwf7bOApf9Yv9BBtR0OnOvx3NSm+ko4U3ywUiLzdxz8CE6mWhLChc39CrZCQ/w2SFwaPsYXQRcHW7l6XPxq+vYGdCWXL4YnHRLp1DQAAA=',
      alt: '', // TODO: write alt
    },
  ],
  'hero': [
    {
      id: 'hero/hero-01',
      src: { full: '/img/hero/hero-01-full.jpg', card: '/img/hero/hero-01-card.jpg', thumb: '/img/hero/hero-01-thumb.jpg' },
      webp: { full: '/img/hero/hero-01-full.webp', card: '/img/hero/hero-01-card.webp', thumb: '/img/hero/hero-01-thumb.webp' },
      width: 1024,
      height: 768,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoUAA8APxFysFAsJqSisAgBgCIJQBWGUAS3gV51vdvFJ15NCAAA/sWdZCNTDpd3jOzs7x5PhuIPPgdBI9/D1/1ZnfnzW5QFmuENb7dm02wfah7HCGSfJTf06IfBpWcX7lgpvWINKrk8C+t+Foc8UmGesT8iXr+9hkjv0O/9/Gf4kVdT+CAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'hero/hero-02',
      src: { full: '/img/hero/hero-02-full.jpg', card: '/img/hero/hero-02-card.jpg', thumb: '/img/hero/hero-02-thumb.jpg' },
      webp: { full: '/img/hero/hero-02-full.webp', card: '/img/hero/hero-02-card.webp', thumb: '/img/hero/hero-02-thumb.webp' },
      width: 1024,
      height: 768,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA8APxFysFAsJqSisAgBgCIJQBOgA9GzXdpSlpK/TKiAAP6aFrRWWDV6eA8gdQEHRV6MklyRPBcOjG4DtXlnigqRbWjsk2z34CzsHTlFQ0n0wzEQLlhpdZwHGN8FcmmNL4+JgxqoAA==',
      alt: '', // TODO: write alt
    },
  ],
  'interior': [
    {
      id: 'interior/interior-01',
      src: { full: '/img/interior/interior-01-full.jpg', card: '/img/interior/interior-01-card.jpg', thumb: '/img/interior/interior-01-thumb.jpg' },
      webp: { full: '/img/interior/interior-01-full.webp', card: '/img/interior/interior-01-card.webp', thumb: '/img/interior/interior-01-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACwBACdASoUAB4APxF0r1AsJqQisAgBgCIJQBWDXAAFTtWGQCzenYQEUMYYJp7AAP4AKkMBDbr51bVykpVCYcgzLwn4M3E3qEkEUL7K+sjwSqOx+v+C1bMqlVaP/vr9ovCFfCc6VaYH260FmqFI+4O+mlgWOsGLCbb9XO/OlmMWyZ+aEgo9qdwUNgkPPg3nNiYaSytXFGg5z5s5BsHh5P3S504AAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-02',
      src: { full: '/img/interior/interior-02-full.jpg', card: '/img/interior/interior-02-card.jpg', thumb: '/img/interior/interior-02-thumb.jpg' },
      webp: { full: '/img/interior/interior-02-full.webp', card: '/img/interior/interior-02-card.webp', thumb: '/img/interior/interior-02-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAQBQCdASoUAB4APxF+slQsKCQjKAqpgCIJQBbZBp37r1s1ZUNYtKqIPE0mmOngnOYAAPj97niIBYbN4Hk3OS+d/GmSx38tPqv3dYPhXPhk3FudRyNgcE4YKcnsNcVqtCNiu5WA8rnVWChIgjenuOBwql3WHImQXyp12qP/KJFtmmAuyCkOkFGOiLBUMiYVZDmXjjwWPnQY+96/liYIlTwRWqpQWK3rLvgAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-03',
      src: { full: '/img/interior/interior-03-full.jpg', card: '/img/interior/interior-03-card.jpg', thumb: '/img/interior/interior-03-thumb.jpg' },
      webp: { full: '/img/interior/interior-03-full.webp', card: '/img/interior/interior-03-card.webp', thumb: '/img/interior/interior-03-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAADQBQCdASoUAB4APxF8slGsKCSisBgIAYAiCWIArC8AOFoXbEHRyPOOkpsPiOU/6UbSvb8CVZ/AAP4jd2iYoeb2cCIR1lr2k1Gwqy3+DrvT77aLVFuumJrI+8AtS5aUOcuSWJufQN2ywH3VnwRA5azLvvxwQjHkOlFQvMVV0kdVWuoPxxliKliq9FT1CeoBhUrm28RO5BNb6WIND6hcVnmjFjspriq9qmdwz5OcxEXOdgsr7rV1cKWOJHWUSSHqoKV2yEkI94ulIWE2CpbeQAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-04',
      src: { full: '/img/interior/interior-04-full.jpg', card: '/img/interior/interior-04-card.jpg', thumb: '/img/interior/interior-04-thumb.jpg' },
      webp: { full: '/img/interior/interior-04-full.webp', card: '/img/interior/interior-04-card.webp', thumb: '/img/interior/interior-04-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwBACdASoUAB4APxF+tlWsJ6SjKAgBgCIJZQDBzFgZ1mItLrTeZ45SaSOesNOvnQAA/udUiNSWIb0BgM/pRJOP7/Xunx/ulJXK6PnyXaYKK43Uy9/xp3GMcKaMABMe745KRhj4ltnPh3tWX7N0mp3JoNh3h5tJG6IGlTmvIRyIiTYsZPbVumj3TZ1w3KEzqcU0T0AfrYcddwXp8ATcrXvBjaZaR2/JfW/OqAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-05',
      src: { full: '/img/interior/interior-05-full.jpg', card: '/img/interior/interior-05-card.jpg', thumb: '/img/interior/interior-05-thumb.jpg' },
      webp: { full: '/img/interior/interior-05-full.webp', card: '/img/interior/interior-05-card.webp', thumb: '/img/interior/interior-05-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoUAB4APxF4sFIsJySisBgIAYAiCWUAwNwyvQuKn2sOJ5OE8UOvgAD9/Fzsj7LAjmp6CEfOX3POi1wVwmNCoyzb3b6G6cOZ22351gwYAnAmVLUVwiLc9qZlesPH+/Y5TLxlnTLGZ2wlj8Wur8GDSDpOnHEMxNQ3wWyvHDbUFImQ5cUudejPwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-06',
      src: { full: '/img/interior/interior-06-full.jpg', card: '/img/interior/interior-06-card.jpg', thumb: '/img/interior/interior-06-thumb.jpg' },
      webp: { full: '/img/interior/interior-06-full.webp', card: '/img/interior/interior-06-card.webp', thumb: '/img/interior/interior-06-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBACdASoUAB4APxF+tlWsJ6SjKAgBgCIJYwC+SD9yz0DTsd7VA1wqdDVV/BrFsYAA/IvYf3aQgo1+MvUHX2jOIZy7s3Nv8JMV5ybR1f1gARTfchoxqei/XDiX2zdzd/uXWuS780Ci4zxhqqf5HGxKRrRQdZ59vduAl7O7W+GUMEQURgOq6WlaC0v52I1l1FgZ38ieJ3dnb/mHp06gAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-07',
      src: { full: '/img/interior/interior-07-full.jpg', card: '/img/interior/interior-07-card.jpg', thumb: '/img/interior/interior-07-thumb.jpg' },
      webp: { full: '/img/interior/interior-07-full.webp', card: '/img/interior/interior-07-card.webp', thumb: '/img/interior/interior-07-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBACdASoUAB4APxF8slQsJ6QjKAqpgCIJZQC7ADMqrv73fa4tkR5t27RlC/mlXEAA/GZDe10dUoBO2Wgwj+NMz3Tz9drgncpoMbImUZ7TpIK60nZC4BPTewL8gRcPU1cAr3K2zpCfbefNeArVGjcx6EfibCrmJnHfQArpWkmKAPZUupTLwbTsx37zEjSlwopfWxYgQLE3YbB/alT8SLRRr8XNEUXveAAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-08',
      src: { full: '/img/interior/interior-08-full.jpg', card: '/img/interior/interior-08-card.jpg', thumb: '/img/interior/interior-08-thumb.jpg' },
      webp: { full: '/img/interior/interior-08-full.webp', card: '/img/interior/interior-08-card.webp', thumb: '/img/interior/interior-08-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQBACdASoUAB4APxF8tFQsJ6SjKAqpgCIJaQDPZDM+xJpgaJjjVFUGp+hZA+HA1AD8ywYfczFlVwpuuY2Sz023ReFLpZPye5t+kR3jMr05AeVO2XuKD3l9s9iukE+pETmrhe0hrccMChGAqBw/iXnrcMqJZtIX551wGo/bvvY2TpvAoaBDonYcO0BaoQNSApXloAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-09',
      src: { full: '/img/interior/interior-09-full.jpg', card: '/img/interior/interior-09-card.jpg', thumb: '/img/interior/interior-09-thumb.jpg' },
      webp: { full: '/img/interior/interior-09-full.webp', card: '/img/interior/interior-09-card.webp', thumb: '/img/interior/interior-09-thumb.webp' },
      width: 1600,
      height: 2428,
      lqip: 'data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADQBACdASoUAB4APxF6tFOsJ6SiqAqpgCIJYgC7ADNI7U50at2SfkaiStkZwSQdAAD+hHSfp7vb5mAbIdkSmCzk3wVgcZQMyyK5MLqzhDjloP5a409Hb6vjdAbP5Ka/6K3jfgzpLiiFwCzE+afHSSpK0sLEhJeCBpSYcF186+uIA28vfATjA/cAJN1ibfozYF4+8qFCJDGt6rvoC6s9TXg5ucTqS/ewQAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-10',
      src: { full: '/img/interior/interior-10-full.jpg', card: '/img/interior/interior-10-card.jpg', thumb: '/img/interior/interior-10-thumb.jpg' },
      webp: { full: '/img/interior/interior-10-full.webp', card: '/img/interior/interior-10-card.webp', thumb: '/img/interior/interior-10-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBQCdASoUAB4APxF0sFAsJySisAgBgCIJZwDPoBdknZRvC+rHEv4EBF9aUlDXU/8EAAD92FlQgwt4ongtgfPxcxstkKSIUQq4nbbxjZkJ7DFPa+gXg/WB3fNatuWYNbTfvGmsXvR7Mi3CUw3qh2V9M94Q0Fzzkn0dww3KcIh/8s4Vk9SMjM+swiaoSUcnGkTfY4OJA47Avj1IOA5gAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-11',
      src: { full: '/img/interior/interior-11-full.jpg', card: '/img/interior/interior-11-card.jpg', thumb: '/img/interior/interior-11-thumb.jpg' },
      webp: { full: '/img/interior/interior-11-full.webp', card: '/img/interior/interior-11-card.webp', thumb: '/img/interior/interior-11-thumb.webp' },
      width: 1441,
      height: 1120,
      lqip: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBkAAAARD6AQQADE37nRiIgYiAWTnfljRxDR/6AZAFZQOCBiAAAAsAMAnQEqFAAQAD8RcrBQLCakorAIAYAiCWMAnQAOyikJ5agRxgAA/c2r40ksnDXXZt9F2a2zaZwdkCGda9cMJ1FzsajUuAC6fX349uGrBQNFFN71YA7MwZan591PUFcmgAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-12',
      src: { full: '/img/interior/interior-12-full.jpg', card: '/img/interior/interior-12-card.jpg', thumb: '/img/interior/interior-12-thumb.jpg' },
      webp: { full: '/img/interior/interior-12-full.webp', card: '/img/interior/interior-12-card.webp', thumb: '/img/interior/interior-12-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD/D4/4iIICQgPPB/rW5BRP+TtwQAVlA4IFwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZwAAUcyt4OJoZAmjYAD+04i4L2CODoZx/nRrcOhMsfvO+q05XlHMOSCk06doDCdsnTRcgxt/4EXaj/4LzyDu3WAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-13',
      src: { full: '/img/interior/interior-13-full.jpg', card: '/img/interior/interior-13-card.jpg', thumb: '/img/interior/interior-13-thumb.jpg' },
      webp: { full: '/img/interior/interior-13-full.webp', card: '/img/interior/interior-13-card.webp', thumb: '/img/interior/interior-13-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBMAAAARD3D7/4iIICQgaP7PtiCi/yHNAFZQOCBeAAAAcAMAnQEqFAAQAD8RcrBQLCakorAIAYAiCUAXYAIF1JKbwYDAAP5V5Et7LiiAgCWDQz43Dia3J4I+G466gEHZPmhmvoRRV4hNH2iuVPjHlijoCUL/ZgxrcC3iR2AAAA==',
      alt: '', // TODO: write alt
    },
  ],
  'offices': [
    {
      id: 'offices/office-01',
      src: { full: '/img/offices/office-01-full.jpg', card: '/img/offices/office-01-card.jpg', thumb: '/img/offices/office-01-thumb.jpg' },
      webp: { full: '/img/offices/office-01-full.webp', card: '/img/offices/office-01-card.webp', thumb: '/img/offices/office-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQC+SywBes2J6zskecIAAP7fn/PyqNQIBFHJ4H29AoI2KdDd9/uLfpRqc2oNZcZ6xZSMn4F4O3jBWOmwRw2WBVVU8ZTfeXKEC2yzNPp8FoWgFSUk9hJZ2eUoMAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'offices/office-02',
      src: { full: '/img/offices/office-02-full.jpg', card: '/img/offices/office-02-card.jpg', thumb: '/img/offices/office-02-thumb.jpg' },
      webp: { full: '/img/offices/office-02-full.webp', card: '/img/offices/office-02-card.webp', thumb: '/img/offices/office-02-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQDG9BDsQaWIckAARwAA++lIncxOGCpItirwb8QnUyZ03/oZQyMp32DvnK41WZ29cFp+TBLEAgh9Dht1vIBAIcOU5xvqC7KsE/Q2PxHenOpJ+BXFxoMY8bfWeB8g6UOQAA==',
      alt: '', // TODO: write alt
    },
  ],
  'services': [
    {
      id: 'services/bedroom-01',
      src: { full: '/img/services/bedroom-01-full.jpg', card: '/img/services/bedroom-01-card.jpg', thumb: '/img/services/bedroom-01-thumb.jpg' },
      webp: { full: '/img/services/bedroom-01-full.webp', card: '/img/services/bedroom-01-card.webp', thumb: '/img/services/bedroom-01-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD3D5/4iIICQgPPB/rW5BRP+TtwQAVlA4IHAAAAAwBACdASoUABAAPxFysFAsJqSisAgBgCIJZwDG9CLt7TiOUpvjyzXU7AAA/sRlflZWISQ1q//Gen951X+Avjjh5JjYhZ3s68ORMBN4UBL43DrkdQIMlEn4FjEe7qMawKDzE+G59s6zPcKgDqAAUlAA',
      alt: '', // TODO: write alt
      roomKind: 'bedroom',
    },
    {
      id: 'services/dining-01',
      src: { full: '/img/services/dining-01-full.jpg', card: '/img/services/dining-01-card.jpg', thumb: '/img/services/dining-01-thumb.jpg' },
      webp: { full: '/img/services/dining-01-full.webp', card: '/img/services/dining-01-card.webp', thumb: '/img/services/dining-01-thumb.webp' },
      width: 1440,
      height: 1120,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJYwCw7AoApxtkrmoMAAD+lC1oje8xPRb4tB7B1aQHCegk8QuVnVfSFO2aFoID5COyb4qU+YSoymhvMeoZZXZEiaeVTbTLMs/o/Hv9ai8pAAAA',
      alt: '', // TODO: write alt
      roomKind: 'dining',
    },
    {
      id: 'services/living-01',
      src: { full: '/img/services/living-01-full.jpg', card: '/img/services/living-01-card.jpg', thumb: '/img/services/living-01-thumb.jpg' },
      webp: { full: '/img/services/living-01-full.webp', card: '/img/services/living-01-card.webp', thumb: '/img/services/living-01-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD/D4/4iIICQgPPB/rW5BRP+TtwQAVlA4IGYAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJYwCsABmOfzHRRcRW6AD3rHgySz2h2wSo1qxUDx0B6+9BhhbZTreaDoJV6MUvRjWSW5798k/ZgN68Q8bZXbSwAOL961SrAebPs9VcAAA=',
      alt: '', // TODO: write alt
      roomKind: 'living',
    },
    {
      id: 'services/meeting-01',
      src: { full: '/img/services/meeting-01-full.jpg', card: '/img/services/meeting-01-card.jpg', thumb: '/img/services/meeting-01-thumb.jpg' },
      webp: { full: '/img/services/meeting-01-full.webp', card: '/img/services/meeting-01-card.webp', thumb: '/img/services/meeting-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQDG9BL8UKUxUC1VcAD76UidzE4YR+Uk3KNFD50Y7UZV0hFGL8LbfcVDnYcWR8jC6Oygd/3fC/bgFYYbc6nBPrm3P0S971TBlkuHC9OGn4O6AI2oEjstku27PrkHzqwKwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'services/villa-01',
      src: { full: '/img/services/villa-01-full.jpg', card: '/img/services/villa-01-card.jpg', thumb: '/img/services/villa-01-thumb.jpg' },
      webp: { full: '/img/services/villa-01-full.webp', card: '/img/services/villa-01-card.webp', thumb: '/img/services/villa-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJQAAKp/E0HBCpNL+5YAD90k26p8ULhV6D+tXWB6PM1QicjZvEwwpEet5Venu705YFX1u4kWH6ce649iijAJHeSYC4Vx+vEvnBQjww4VeGxLc7HieaIoJSYMeiHROaEHVlFQAA',
      alt: '', // TODO: write alt
    },
  ],
};
