/* eslint-disable */
// GENERATED by scripts/process-images.mjs — do not edit by hand.
// Alt text is written in src/data/projects/*.ts, never here.
// 76 images across 7 folders.

import type { ImageAsset } from '@/types/project';

/** Sources narrower than 1600px; `full` is capped at true width. Re-supply. */
export const LOW_RES: readonly string[] = [
  "commercial/commercial-01 (1100 × 733 px)",
  "commercial/commercial-02 (1100 × 733 px)",
  "commercial/commercial-03 (1280 × 1050 px)",
  "commercial/commercial-04 (1515 × 1200 px)",
  "commercial/commercial-05 (1515 × 1200 px)",
  "commercial/commercial-06 (1515 × 1200 px)",
  "commercial/commercial-10 (1024 × 576 px)",
  "commercial/commercial-11 (1024 × 576 px)",
  "flats/flat-01 (1441 × 1121 px)",
  "flats/flat-02 (1200 × 995 px)",
  "flats/flat-03 (1200 × 1063 px)",
  "flats/flat-04 (1200 × 995 px)",
  "flats/flat-05 (1200 × 1003 px)",
  "flats/flat-06 (1200 × 975 px)",
  "flats/flat-07 (1200 × 830 px)",
  "flats/flat-08 (1200 × 912 px)",
  "flats/flat-09 (1200 × 844 px)",
  "flats/flat-10 (1200 × 708 px)",
  "flats/flat-11 (1200 × 926 px)",
  "flats/flat-12 (1200 × 960 px)",
  "flats/flat-13 (1200 × 800 px)",
  "flats/flat-14 (1200 × 800 px)",
  "hero/hero-01 (1024 × 768 px)",
  "hero/hero-02 (1024 × 768 px)",
  "interior/interior-11 (1441 × 1120 px)",
  "interior/interior-12 (1441 × 1121 px)",
  "interior/interior-13 (1440 × 1121 px)",
  "interior/interior-14 (1549 × 1200 px)",
  "interior/interior-15 (1518 × 1200 px)",
  "interior/interior-19 (1200 × 800 px)",
  "interior/interior-20 (1200 × 849 px)",
  "interior/interior-21 (1200 × 945 px)",
  "interior/interior-22 (1280 × 853 px)",
  "interior/interior-23 (1050 × 560 px)",
  "interior/interior-24 (1280 × 853 px)",
  "interior/interior-25 (1050 × 560 px)",
  "interior/interior-30 (1576 × 1200 px)",
  "interior/interior-31 (1552 × 1200 px)",
  "interior/interior-32 (1415 × 1200 px)",
  "interior/interior-34 (1280 × 853 px)",
  "interior/interior-35 (1280 × 853 px)",
  "interior/interior-36 (1519 × 1200 px)",
  "offices/office-01 (1441 × 1121 px)",
  "offices/office-02 (1441 × 1121 px)",
  "services/bedroom-01 (1440 × 1121 px)",
  "services/dining-01 (1440 × 1120 px)",
  "services/living-01 (1440 × 1121 px)",
  "services/meeting-01 (1441 × 1121 px)",
  "services/villa-01 (1441 × 1121 px)"
];

export const generatedImages: Record<string, ImageAsset[]> = {
  'architecture': [
    {
      id: 'architecture/architecture-01',
      src: { full: '/img/architecture/architecture-01-full.jpg', card: '/img/architecture/architecture-01-card.jpg', thumb: '/img/architecture/architecture-01-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-01-full.webp', card: '/img/architecture/architecture-01-card.webp', thumb: '/img/architecture/architecture-01-thumb.webp' },
      width: 1600,
      height: 1660,
      lqip: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAADwBACdASoUABUAPxGAuFWsKCUjKAgBgCIJQBb3AjB2E6BxoBj38fetsmLQ4FT41QAA/tQSw8PhfXXhUa5IMgCfIoeaGvFUbK5j2JuJ8iSGAYBNlnbja1MeccOvdRs+SgsiIbc0zZH3cmG3Iosk8hE6mpxpfTIm8VL1i0M/BDjZrrKkS+PMQVdBbTm8aD65ju8s917whw4NAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'architecture/architecture-02',
      src: { full: '/img/architecture/architecture-02-full.jpg', card: '/img/architecture/architecture-02-card.jpg', thumb: '/img/architecture/architecture-02-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-02-full.webp', card: '/img/architecture/architecture-02-card.webp', thumb: '/img/architecture/architecture-02-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAAAwBQCdASoUAB4APxF4slIsJySisBgIAYAiCUAWHYWZ/7hvvrF0zPWOXgaCApWKXElW8AD+l/fLkgj2S6xk00rtpoi5yE4MrXUg2yCqrvH0l2lsWIbKlDOZD9HT3S/kGPS9DfVvka7An4RqfgZu+x/5Vwpcs3QW8nu/CDy1G/DfkkZ/4+GYRaY396JvsQhOploSwoXNzhVeYGqDFr9IXReE2PkPwrc4k1dT3fhJgmzlImJJHUb+4AAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'architecture/architecture-03',
      src: { full: '/img/architecture/architecture-03-full.jpg', card: '/img/architecture/architecture-03-card.jpg', thumb: '/img/architecture/architecture-03-thumb.jpg' },
      webp: { full: '/img/architecture/architecture-03-full.webp', card: '/img/architecture/architecture-03-card.webp', thumb: '/img/architecture/architecture-03-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAABwBQCdASoUAB4APxF6slQsJ6QjKAqpgCIJYgCw7Azqkv4+xZXYu0CecUzILkeSxF0W/GEAAOJ9XxPYbsstprPqft0YVykkN17k81kThAD1m3mYSdHIAjpgHCXCAIGizCEOjY0LgYbvWGT6kyrIS6+ouARtHSIJ+iSXT+vdkwUh/FW6iQnJspxiZ2AxJ56ETsrx6sv7QHzhAgQV+nBNnf2D5njuy/ToETKksEd3lsZxxHXAAAA=',
      alt: '', // TODO: write alt
    },
  ],
  'commercial': [
    {
      id: 'commercial/commercial-01',
      src: { full: '/img/commercial/commercial-01-full.jpg', card: '/img/commercial/commercial-01-card.jpg', thumb: '/img/commercial/commercial-01-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-01-full.webp', card: '/img/commercial/commercial-01-card.webp', thumb: '/img/commercial/commercial-01-thumb.webp' },
      width: 1100,
      height: 733,
      lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwAATt9xWZzpGbk1gAD+Xt9Aq4jodnyvI8qGZYgiVAsphSr0OnDZxAUnrFF3VPQEDWY2SgGZuhw0C5YHfNLU6AAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-02',
      src: { full: '/img/commercial/commercial-02-full.jpg', card: '/img/commercial/commercial-02-card.jpg', thumb: '/img/commercial/commercial-02-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-02-full.webp', card: '/img/commercial/commercial-02-card.webp', thumb: '/img/commercial/commercial-02-thumb.webp' },
      width: 1100,
      height: 733,
      lqip: 'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwCsAA8LtWZO2OQAAPElt+C0NtkFtHaS5l0msC5CVZPJUldrpNY+EQcCl5xQR+nA6B2RwaZ9vfRdwuvr/Ll0AAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-03',
      src: { full: '/img/commercial/commercial-03-full.jpg', card: '/img/commercial/commercial-03-card.jpg', thumb: '/img/commercial/commercial-03-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-03-full.webp', card: '/img/commercial/commercial-03-card.webp', thumb: '/img/commercial/commercial-03-thumb.webp' },
      width: 1280,
      height: 1050,
      lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUABAAPxFwsFAsJiSisAgBgCIJQBYdhFgJtbA/e+jmP4FTrjYAziQA6c7kXnilru0pQue9CQDo8FLmIc7nQvf535xTm2pAOVsEAEPRROEmCXmFpsD+RfKCuhg0yyLzlxgAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-04',
      src: { full: '/img/commercial/commercial-04-full.jpg', card: '/img/commercial/commercial-04-card.jpg', thumb: '/img/commercial/commercial-04-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-04-full.webp', card: '/img/commercial/commercial-04-card.webp', thumb: '/img/commercial/commercial-04-thumb.webp' },
      width: 1515,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoUABAAPxFysFAsJqSisAgBgCIJZwDImywBrXDeo7YHyG+LdvoAAMo+QlJXC6jDN9JeXFu2e7cY1LdGzpVqhbTbTDXA2FwKzarzFcgRMee1rYa1NZWBNimP2xi9wJSTBzNWH4vfIHlGRsOIAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-05',
      src: { full: '/img/commercial/commercial-05-full.jpg', card: '/img/commercial/commercial-05-card.jpg', thumb: '/img/commercial/commercial-05-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-05-full.webp', card: '/img/commercial/commercial-05-card.webp', thumb: '/img/commercial/commercial-05-thumb.webp' },
      width: 1515,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUABAAPxFysFAsJqSisAgBgCIJZwC90ywBKs05T3QF+vhRwAD4SPBrxaMS29ePvjRux6+xlPVo/up611DzTSbvFzANFojjFlu/U/N8UVaQfd4oUpWyzx0UT1BlVTofk8IrxWarXXLb5gAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-06',
      src: { full: '/img/commercial/commercial-06-full.jpg', card: '/img/commercial/commercial-06-card.jpg', thumb: '/img/commercial/commercial-06-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-06-full.webp', card: '/img/commercial/commercial-06-card.webp', thumb: '/img/commercial/commercial-06-thumb.webp' },
      width: 1515,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoUABAAPxFysFAsJqSisAgBgCIJYwC+TagBVpOreiaM1UwQAAD+Z7522PpmXhC00Iw990mdwo0QU+GdllbpBq6ALCl1pTPzBgn8eXBkqA8+BTok2juJe81mwq+ljTw13mPhHEsZkT3E2mn7cxfBA+6Da4uEJDUmpwAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-07',
      src: { full: '/img/commercial/commercial-07-full.jpg', card: '/img/commercial/commercial-07-card.jpg', thumb: '/img/commercial/commercial-07-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-07-full.webp', card: '/img/commercial/commercial-07-card.webp', thumb: '/img/commercial/commercial-07-thumb.webp' },
      width: 1600,
      height: 900,
      lqip: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoUAAsAPxFwsFAsJiSisAgBgCIJYwC06CINeOTRCvwOz8JwAAD+k42oMhs4DQrV7LwudF68Fh4VUlR6ttX7PijPAmEwKV1dWdohmgpUtl00HfrEyy2eE7Kko7wAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-08',
      src: { full: '/img/commercial/commercial-08-full.jpg', card: '/img/commercial/commercial-08-card.jpg', thumb: '/img/commercial/commercial-08-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-08-full.webp', card: '/img/commercial/commercial-08-card.webp', thumb: '/img/commercial/commercial-08-thumb.webp' },
      width: 1600,
      height: 900,
      lqip: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4WAoAAAAQAAAAEwAACgAAQUxQSBMAAAARD9D/iAiIaQiX/qlNhIj+J1MCAFZQOCBsAAAA0AMAnQEqFAALAD8RcrBQLCakorAIAYAiCWgAnQAbc8iRnRJkR5yAAP5gl+hkk4gdTN0plfYRQqHb35e8DF4g1r9Kn/4WbxFd1k4HJ/XPr08OQUPbd+7P0SgNZINwPHB1AjlWcfGlBZDzYaAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-09',
      src: { full: '/img/commercial/commercial-09-full.jpg', card: '/img/commercial/commercial-09-card.jpg', thumb: '/img/commercial/commercial-09-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-09-full.webp', card: '/img/commercial/commercial-09-card.webp', thumb: '/img/commercial/commercial-09-thumb.webp' },
      width: 1600,
      height: 900,
      lqip: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoUAAsAPxFysFCsJqSisAgBgCIJYwC06A3bUCQXFZkAAP5TFAQTxysyPcj2f+gGvtWkocdEuPuJkT66LNYewkETFZCExK3sRw5FXyn//hnWwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-10',
      src: { full: '/img/commercial/commercial-10-full.jpg', card: '/img/commercial/commercial-10-card.jpg', thumb: '/img/commercial/commercial-10-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-10-full.webp', card: '/img/commercial/commercial-10-card.webp', thumb: '/img/commercial/commercial-10-thumb.webp' },
      width: 1024,
      height: 576,
      lqip: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAAsAPxFysVCsJqSisAgBgCIJZQC+SBrKY8Pxr1dcwADJ6f66wfaRDK1leGNQZx00pHS+jG+S2EEhBV5Rty3CqrSUzAP9Ugs7euaLQd9ggAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-11',
      src: { full: '/img/commercial/commercial-11-full.jpg', card: '/img/commercial/commercial-11-card.jpg', thumb: '/img/commercial/commercial-11-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-11-full.webp', card: '/img/commercial/commercial-11-card.webp', thumb: '/img/commercial/commercial-11-thumb.webp' },
      width: 1024,
      height: 576,
      lqip: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBACdASoUAAsAPxFysVAsJqSisAgBgCIJZwDDNCHw4oxkXwNlWfwGgAD+uoIp84vzAxpQtd0r+ab6Qav3nFpORO2NGS/YVddajsgC48dGd813kss5Dnj3LHq9Pq05yINEAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'commercial/commercial-12',
      src: { full: '/img/commercial/commercial-12-full.jpg', card: '/img/commercial/commercial-12-card.jpg', thumb: '/img/commercial/commercial-12-thumb.jpg' },
      webp: { full: '/img/commercial/commercial-12-full.webp', card: '/img/commercial/commercial-12-card.webp', thumb: '/img/commercial/commercial-12-thumb.webp' },
      width: 1600,
      height: 900,
      lqip: 'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACwAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYwC06B5ea4oMIEsrQAD+UlDteTODdmkbJJfatJRBS3X+KF09miFAxHLVXIqBbXakzAugkIJxFBgXhubk4RGMAAA=',
      alt: '', // TODO: write alt
    },
  ],
  'flats': [
    {
      id: 'flats/flat-01',
      src: { full: '/img/flats/flat-01-full.jpg', card: '/img/flats/flat-01-card.jpg', thumb: '/img/flats/flat-01-thumb.jpg' },
      webp: { full: '/img/flats/flat-01-full.webp', card: '/img/flats/flat-01-card.webp', thumb: '/img/flats/flat-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQAwCdASoUABAAPxFysFAsJqSisAgBgCIJQAAKohFBgGMLUyIAAP3STbqoAkanZFPj+wL6Q58tAdKFk0O5NW6ms6Szm1pVD7lGFvjbgMmsexRRgDl9GzbSoV6ztVgbTj5pinAJJ6p/oSz0k3iOYfQ9ER9WUVAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-02',
      src: { full: '/img/flats/flat-02-full.jpg', card: '/img/flats/flat-02-card.jpg', thumb: '/img/flats/flat-02-thumb.jpg' },
      webp: { full: '/img/flats/flat-02-full.webp', card: '/img/flats/flat-02-card.webp', thumb: '/img/flats/flat-02-thumb.webp' },
      width: 1200,
      height: 995,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUABEAPxF6slQsJyQjKAqpgCIJZQCzgBElt02wLXa5qXeKBAD+WQbyowqEIkug4nEy3WXOGZmfojIfMzK2cXmzGC0GXFF3t/8bOQHjaf3T6nYE/0knAaCR3mYFWiYRCoVqU5B+OJONYqKKPAWMAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-03',
      src: { full: '/img/flats/flat-03-full.jpg', card: '/img/flats/flat-03-card.jpg', thumb: '/img/flats/flat-03-thumb.jpg' },
      webp: { full: '/img/flats/flat-03-full.webp', card: '/img/flats/flat-03-card.webp', thumb: '/img/flats/flat-03-thumb.webp' },
      width: 1200,
      height: 1063,
      lqip: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBQCdASoUABIAPxF+tlWsJ6SjKAgBgCIJQBdgZYAMRRjQBm59l1iirfZnnl6vWyDgAP5T9d/ee+zq9V+hJPNmFFvrynOLh4+JxfqUpRrnCWHIbkgroJCuiMcQTkcwtjnmEuybpWuWy5aUIrcOvNlSblFRN0dVXYBQjNH7anFmYqStxFvOkDcquLBVIe1Iqr4J9RbFovx9CZjbRmoAAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-04',
      src: { full: '/img/flats/flat-04-full.jpg', card: '/img/flats/flat-04-card.jpg', thumb: '/img/flats/flat-04-thumb.jpg' },
      webp: { full: '/img/flats/flat-04-full.webp', card: '/img/flats/flat-04-card.webp', thumb: '/img/flats/flat-04-thumb.webp' },
      width: 1200,
      height: 995,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUABEAPxF6tlMsJ6UkKAqpgCIJZQCnFBEzj7ki0ipF2CrugAD+UdqWPic+3syJsPLmMogtC6Lb3tnmUiB+P0r5x9Anl3zOQ58/exYfUyWDj3c0Lgjz6fkV2aAzosiNoiWgBASAll3Mf56iAavYAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-05',
      src: { full: '/img/flats/flat-05-full.jpg', card: '/img/flats/flat-05-card.jpg', thumb: '/img/flats/flat-05-thumb.jpg' },
      webp: { full: '/img/flats/flat-05-full.webp', card: '/img/flats/flat-05-card.webp', thumb: '/img/flats/flat-05-thumb.webp' },
      width: 1200,
      height: 1003,
      lqip: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACwAwCdASoUABEAPxF6tVOsJ6UiqAqpgCIJZADE2AbvAXwXFszYYAD+FiNIrrb/6eVLp0Nh1hwLcmrczw2dVvXSGAF5x/bos0JDVrnR61cNDcbXpdw8Sr/WUW6PmKmh+qEazq6gOIvJu09axFwqm+fzZ5AAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-06',
      src: { full: '/img/flats/flat-06-full.jpg', card: '/img/flats/flat-06-card.jpg', thumb: '/img/flats/flat-06-thumb.jpg' },
      webp: { full: '/img/flats/flat-06-full.webp', card: '/img/flats/flat-06-card.webp', thumb: '/img/flats/flat-06-thumb.webp' },
      width: 1200,
      height: 975,
      lqip: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACQAwCdASoUABAAPxFysFAsJqSisAgBgCIJaACo9BWhsg1waLF4APcbuc2RpdXcm9l2+ez1fK6DTYeN6AFz4kUmQiw7eJdLNFzCyYBdF9BoiCPn9Dp0ai/jekJesHTA39p7/EsPVWCnIJBVFxZH8iD9gzSAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-07',
      src: { full: '/img/flats/flat-07-full.jpg', card: '/img/flats/flat-07-card.jpg', thumb: '/img/flats/flat-07-thumb.jpg' },
      webp: { full: '/img/flats/flat-07-full.webp', card: '/img/flats/flat-07-card.webp', thumb: '/img/flats/flat-07-thumb.webp' },
      width: 1200,
      height: 830,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQBACdASoUAA4APxFysFCsJqSisAgBgCIJZgCdLwABD/w+spv2nyzEAAD8jCcNojW3beryv2B42hKhoRigtqocVurOmC2YRNHRK0NmLmm5vbrrJ+GaqKO0P7h3FvDjNOmf0jO2vrwnr9AA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-08',
      src: { full: '/img/flats/flat-08-full.jpg', card: '/img/flats/flat-08-card.jpg', thumb: '/img/flats/flat-08-thumb.jpg' },
      webp: { full: '/img/flats/flat-08-full.webp', card: '/img/flats/flat-08-card.webp', thumb: '/img/flats/flat-08-thumb.webp' },
      width: 1200,
      height: 912,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAA8APxFwsFAsJiSisAgBgCIJQBdgAzw97610tpUX9gAA/sv3dWl9NUypHQsMDh05YhOQ/+svNAWUXrug/+DLO7rKAyRSKWq+eb9sqN+s/8oG2OLrGFFTXsBI2G3swuAdu4AA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-09',
      src: { full: '/img/flats/flat-09-full.jpg', card: '/img/flats/flat-09-card.jpg', thumb: '/img/flats/flat-09-thumb.jpg' },
      webp: { full: '/img/flats/flat-09-full.webp', card: '/img/flats/flat-09-card.webp', thumb: '/img/flats/flat-09-thumb.webp' },
      width: 1200,
      height: 844,
      lqip: 'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoUAA4APxFysVCsJqSisAgBgCIJZgCdACPbu6FwgOjOnBCeAAD8jCcIz5WA1bKJ7iP5Gi1rq5YPblKSIbXKJzETlhz7A0JTUbT91CNAqK6Ptx7cV4QGu8SqVTVGjga64uJ/09Lh3KxoAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-10',
      src: { full: '/img/flats/flat-10-full.jpg', card: '/img/flats/flat-10-card.jpg', thumb: '/img/flats/flat-10-thumb.jpg' },
      webp: { full: '/img/flats/flat-10-full.webp', card: '/img/flats/flat-10-card.webp', thumb: '/img/flats/flat-10-thumb.webp' },
      width: 1200,
      height: 708,
      lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwAwCdASoUAAwAPxFysVCsJqSisAgBgCIJQBOgBFEURs52jFxvgAD+WH7jD34Ov+RaTZuS6auxxlXQMz54I4SJcLQa1WKxCDB1RxUj9qqiF2ZCpihDCZQaPAPWY/37afPDuAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-11',
      src: { full: '/img/flats/flat-11-full.jpg', card: '/img/flats/flat-11-card.jpg', thumb: '/img/flats/flat-11-thumb.jpg' },
      webp: { full: '/img/flats/flat-11-full.webp', card: '/img/flats/flat-11-card.webp', thumb: '/img/flats/flat-11-thumb.webp' },
      width: 1200,
      height: 926,
      lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAA8APxFysFAsJqSisAgBgCIJQBdgA9K+FC6SQQ+KHMAA/svsavi2fTV+sr/WTTPD1FJLCGXDWIbXilIXo3ZW9L1RiTCxeVZxiJxcvLWxuxAEzVsKKmvYCRneeJdBCtaAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-12',
      src: { full: '/img/flats/flat-12-full.jpg', card: '/img/flats/flat-12-card.jpg', thumb: '/img/flats/flat-12-thumb.jpg' },
      webp: { full: '/img/flats/flat-12-full.webp', card: '/img/flats/flat-12-card.webp', thumb: '/img/flats/flat-12-thumb.webp' },
      width: 1200,
      height: 960,
      lqip: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoUABAAPxFwsFAsJiSisAgBgCIJYgC7ACG9FlEV2On3btwA0AD+w7gsEY0ahxKWMmRd+j1J2NTZQnTbkB72XLcZQzYl2Fvhr6DtOiZe1NwqhOt+NX4pvNfl8AT9293qpYFW2b6ONtmjMa38ysxaV3cAAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-13',
      src: { full: '/img/flats/flat-13-full.jpg', card: '/img/flats/flat-13-card.jpg', thumb: '/img/flats/flat-13-thumb.jpg' },
      webp: { full: '/img/flats/flat-13-full.webp', card: '/img/flats/flat-13-card.webp', thumb: '/img/flats/flat-13-thumb.webp' },
      width: 1200,
      height: 800,
      lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABwAwCdASoUAA0APxFysFAsJqSisAgBgCIJZAC7ABSlHUEDsgAA/HiWcn3hHmiOFBceGMkHD8Sz+mYIh6xcMVUY/2eljwypqO6S2asjaKlt68s2UU/QVQRjmgE3gKzjr/sJdldXRmQAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'flats/flat-14',
      src: { full: '/img/flats/flat-14-full.jpg', card: '/img/flats/flat-14-card.jpg', thumb: '/img/flats/flat-14-thumb.jpg' },
      webp: { full: '/img/flats/flat-14-full.webp', card: '/img/flats/flat-14-card.webp', thumb: '/img/flats/flat-14-thumb.webp' },
      width: 1200,
      height: 800,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBACdASoUAA0APxFysFAsJqSisAgBgCIJYgCADBBuBW/4BdY43sivypxgAPxUMY96QQlOV/fo2N+muD7UdXyRAQG6DlJCV0rSoWqsyvXsYI+RGse76WVtLXKc4Z5SZ+ezZ89MQQsZrCq9SNAAAA==',
      alt: '', // TODO: write alt
    },
  ],
  'hero': [
    {
      id: 'hero/hero-01',
      src: { full: '/img/hero/hero-01-full.jpg', card: '/img/hero/hero-01-card.jpg', thumb: '/img/hero/hero-01-thumb.jpg' },
      webp: { full: '/img/hero/hero-01-full.webp', card: '/img/hero/hero-01-card.webp', thumb: '/img/hero/hero-01-thumb.webp' },
      width: 1024,
      height: 768,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoUAA8APxFysFAsJqSisAgBgCIJQBWGUAS3gV51vdvFJ15NCAAA/sWdZCNTDpd3jOzs7x5PhuIPPgdBI9/D1/1ZnfnzW5QFmuENb7dm02wfah7HCGSfJTf06IfBpWcX7lgpvWINKrk8C+t+Foc8UmGesT8iXr+9hkjv0O/9/Gf4kVdT+CAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'hero/hero-02',
      src: { full: '/img/hero/hero-02-full.jpg', card: '/img/hero/hero-02-card.jpg', thumb: '/img/hero/hero-02-thumb.jpg' },
      webp: { full: '/img/hero/hero-02-full.webp', card: '/img/hero/hero-02-card.webp', thumb: '/img/hero/hero-02-thumb.webp' },
      width: 1024,
      height: 768,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA8APxFysFAsJqSisAgBgCIJQBOgA9GzXdpSlpK/TKiAAP6aFrRWWDV6eA8gdQEHRV6MklyRPBcOjG4DtXlnigqRbWjsk2z34CzsHTlFQ0n0wzEQLlhpdZwHGN8FcmmNL4+JgxqoAA==',
      alt: '', // TODO: write alt
    },
  ],
  'interior': [
    {
      id: 'interior/interior-01',
      src: { full: '/img/interior/interior-01-full.jpg', card: '/img/interior/interior-01-card.jpg', thumb: '/img/interior/interior-01-thumb.jpg' },
      webp: { full: '/img/interior/interior-01-full.webp', card: '/img/interior/interior-01-card.webp', thumb: '/img/interior/interior-01-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAACwBACdASoUAB4APxF0r1AsJqQisAgBgCIJQBWDXAAFTtWGQCzenYQEUMYYJp7AAP4AKkMBDbr51bVykpVCYcgzLwn4M3E3qEkEUL7K+sjwSqOx+v+C1bMqlVaP/vr9ovCFfCc6VaYH260FmqFI+4O+mlgWOsGLCbb9XO/OlmMWyZ+aEgo9qdwUNgkPPg3nNiYaSytXFGg5z5s5BsHh5P3S504AAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-02',
      src: { full: '/img/interior/interior-02-full.jpg', card: '/img/interior/interior-02-card.jpg', thumb: '/img/interior/interior-02-thumb.jpg' },
      webp: { full: '/img/interior/interior-02-full.webp', card: '/img/interior/interior-02-card.webp', thumb: '/img/interior/interior-02-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAQBQCdASoUAB4APxF+slQsKCQjKAqpgCIJQBbZBp37r1s1ZUNYtKqIPE0mmOngnOYAAPj97niIBYbN4Hk3OS+d/GmSx38tPqv3dYPhXPhk3FudRyNgcE4YKcnsNcVqtCNiu5WA8rnVWChIgjenuOBwql3WHImQXyp12qP/KJFtmmAuyCkOkFGOiLBUMiYVZDmXjjwWPnQY+96/liYIlTwRWqpQWK3rLvgAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-03',
      src: { full: '/img/interior/interior-03-full.jpg', card: '/img/interior/interior-03-card.jpg', thumb: '/img/interior/interior-03-thumb.jpg' },
      webp: { full: '/img/interior/interior-03-full.webp', card: '/img/interior/interior-03-card.webp', thumb: '/img/interior/interior-03-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAADQBQCdASoUAB4APxF8slGsKCSisBgIAYAiCWIArC8AOFoXbEHRyPOOkpsPiOU/6UbSvb8CVZ/AAP4jd2iYoeb2cCIR1lr2k1Gwqy3+DrvT77aLVFuumJrI+8AtS5aUOcuSWJufQN2ywH3VnwRA5azLvvxwQjHkOlFQvMVV0kdVWuoPxxliKliq9FT1CeoBhUrm28RO5BNb6WIND6hcVnmjFjspriq9qmdwz5OcxEXOdgsr7rV1cKWOJHWUSSHqoKV2yEkI94ulIWE2CpbeQAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-04',
      src: { full: '/img/interior/interior-04-full.jpg', card: '/img/interior/interior-04-card.jpg', thumb: '/img/interior/interior-04-thumb.jpg' },
      webp: { full: '/img/interior/interior-04-full.webp', card: '/img/interior/interior-04-card.webp', thumb: '/img/interior/interior-04-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAADwBACdASoUAB4APxF+tlWsJ6SjKAgBgCIJZQDBzFgZ1mItLrTeZ45SaSOesNOvnQAA/udUiNSWIb0BgM/pRJOP7/Xunx/ulJXK6PnyXaYKK43Uy9/xp3GMcKaMABMe745KRhj4ltnPh3tWX7N0mp3JoNh3h5tJG6IGlTmvIRyIiTYsZPbVumj3TZ1w3KEzqcU0T0AfrYcddwXp8ATcrXvBjaZaR2/JfW/OqAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-05',
      src: { full: '/img/interior/interior-05-full.jpg', card: '/img/interior/interior-05-card.jpg', thumb: '/img/interior/interior-05-thumb.jpg' },
      webp: { full: '/img/interior/interior-05-full.webp', card: '/img/interior/interior-05-card.webp', thumb: '/img/interior/interior-05-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBACdASoUAB4APxF4sFIsJySisBgIAYAiCWUAwNwyvQuKn2sOJ5OE8UOvgAD9/Fzsj7LAjmp6CEfOX3POi1wVwmNCoyzb3b6G6cOZ22351gwYAnAmVLUVwiLc9qZlesPH+/Y5TLxlnTLGZ2wlj8Wur8GDSDpOnHEMxNQ3wWyvHDbUFImQ5cUudejPwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-06',
      src: { full: '/img/interior/interior-06-full.jpg', card: '/img/interior/interior-06-card.jpg', thumb: '/img/interior/interior-06-thumb.jpg' },
      webp: { full: '/img/interior/interior-06-full.webp', card: '/img/interior/interior-06-card.webp', thumb: '/img/interior/interior-06-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwBACdASoUAB4APxF+tlWsJ6SjKAgBgCIJYwC+SD9yz0DTsd7VA1wqdDVV/BrFsYAA/IvYf3aQgo1+MvUHX2jOIZy7s3Nv8JMV5ybR1f1gARTfchoxqei/XDiX2zdzd/uXWuS780Ci4zxhqqf5HGxKRrRQdZ59vduAl7O7W+GUMEQURgOq6WlaC0v52I1l1FgZ38ieJ3dnb/mHp06gAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-07',
      src: { full: '/img/interior/interior-07-full.jpg', card: '/img/interior/interior-07-card.jpg', thumb: '/img/interior/interior-07-thumb.jpg' },
      webp: { full: '/img/interior/interior-07-full.webp', card: '/img/interior/interior-07-card.webp', thumb: '/img/interior/interior-07-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAADwBACdASoUAB4APxF8slQsJ6QjKAqpgCIJZQC7ADMqrv73fa4tkR5t27RlC/mlXEAA/GZDe10dUoBO2Wgwj+NMz3Tz9drgncpoMbImUZ7TpIK60nZC4BPTewL8gRcPU1cAr3K2zpCfbefNeArVGjcx6EfibCrmJnHfQArpWkmKAPZUupTLwbTsx37zEjSlwopfWxYgQLE3YbB/alT8SLRRr8XNEUXveAAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-08',
      src: { full: '/img/interior/interior-08-full.jpg', card: '/img/interior/interior-08-card.jpg', thumb: '/img/interior/interior-08-thumb.jpg' },
      webp: { full: '/img/interior/interior-08-full.webp', card: '/img/interior/interior-08-card.webp', thumb: '/img/interior/interior-08-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADQBACdASoUAB4APxF8tFQsJ6SjKAqpgCIJaQDPZDM+xJpgaJjjVFUGp+hZA+HA1AD8ywYfczFlVwpuuY2Sz023ReFLpZPye5t+kR3jMr05AeVO2XuKD3l9s9iukE+pETmrhe0hrccMChGAqBw/iXnrcMqJZtIX551wGo/bvvY2TpvAoaBDonYcO0BaoQNSApXloAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-09',
      src: { full: '/img/interior/interior-09-full.jpg', card: '/img/interior/interior-09-card.jpg', thumb: '/img/interior/interior-09-thumb.jpg' },
      webp: { full: '/img/interior/interior-09-full.webp', card: '/img/interior/interior-09-card.webp', thumb: '/img/interior/interior-09-thumb.webp' },
      width: 1600,
      height: 2428,
      lqip: 'data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADQBACdASoUAB4APxF6tFOsJ6SiqAqpgCIJYgC7ADNI7U50at2SfkaiStkZwSQdAAD+hHSfp7vb5mAbIdkSmCzk3wVgcZQMyyK5MLqzhDjloP5a409Hb6vjdAbP5Ka/6K3jfgzpLiiFwCzE+afHSSpK0sLEhJeCBpSYcF186+uIA28vfATjA/cAJN1ibfozYF4+8qFCJDGt6rvoC6s9TXg5ucTqS/ewQAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-10',
      src: { full: '/img/interior/interior-10-full.jpg', card: '/img/interior/interior-10-card.jpg', thumb: '/img/interior/interior-10-thumb.jpg' },
      webp: { full: '/img/interior/interior-10-full.webp', card: '/img/interior/interior-10-card.webp', thumb: '/img/interior/interior-10-thumb.webp' },
      width: 1600,
      height: 2400,
      lqip: 'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBQCdASoUAB4APxF0sFAsJySisAgBgCIJZwDPoBdknZRvC+rHEv4EBF9aUlDXU/8EAAD92FlQgwt4ongtgfPxcxstkKSIUQq4nbbxjZkJ7DFPa+gXg/WB3fNatuWYNbTfvGmsXvR7Mi3CUw3qh2V9M94Q0Fzzkn0dww3KcIh/8s4Vk9SMjM+swiaoSUcnGkTfY4OJA47Avj1IOA5gAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-11',
      src: { full: '/img/interior/interior-11-full.jpg', card: '/img/interior/interior-11-card.jpg', thumb: '/img/interior/interior-11-thumb.jpg' },
      webp: { full: '/img/interior/interior-11-full.webp', card: '/img/interior/interior-11-card.webp', thumb: '/img/interior/interior-11-thumb.webp' },
      width: 1441,
      height: 1120,
      lqip: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBkAAAARD6AQQADE37nRiIgYiAWTnfljRxDR/6AZAFZQOCBiAAAAsAMAnQEqFAAQAD8RcrBQLCakorAIAYAiCWMAnQAOyikJ5agRxgAA/c2r40ksnDXXZt9F2a2zaZwdkCGda9cMJ1FzsajUuAC6fX349uGrBQNFFN71YA7MwZan591PUFcmgAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-12',
      src: { full: '/img/interior/interior-12-full.jpg', card: '/img/interior/interior-12-card.jpg', thumb: '/img/interior/interior-12-thumb.jpg' },
      webp: { full: '/img/interior/interior-12-full.webp', card: '/img/interior/interior-12-card.webp', thumb: '/img/interior/interior-12-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD/D4/4iIICQgPPB/rW5BRP+TtwQAVlA4IFwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZwAAUcyt4OJoZAmjYAD+04i4L2CODoZx/nRrcOhMsfvO+q05XlHMOSCk06doDCdsnTRcgxt/4EXaj/4LzyDu3WAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-13',
      src: { full: '/img/interior/interior-13-full.jpg', card: '/img/interior/interior-13-card.jpg', thumb: '/img/interior/interior-13-thumb.jpg' },
      webp: { full: '/img/interior/interior-13-full.webp', card: '/img/interior/interior-13-card.webp', thumb: '/img/interior/interior-13-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBMAAAARD3D7/4iIICQgaP7PtiCi/yHNAFZQOCBeAAAAcAMAnQEqFAAQAD8RcrBQLCakorAIAYAiCUAXYAIF1JKbwYDAAP5V5Et7LiiAgCWDQz43Dia3J4I+G466gEHZPmhmvoRRV4hNH2iuVPjHlijoCUL/ZgxrcC3iR2AAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-14',
      src: { full: '/img/interior/interior-14-full.jpg', card: '/img/interior/interior-14-card.jpg', thumb: '/img/interior/interior-14-thumb.jpg' },
      webp: { full: '/img/interior/interior-14-full.webp', card: '/img/interior/interior-14-card.webp', thumb: '/img/interior/interior-14-thumb.webp' },
      width: 1549,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQAAH2I9E/wYoAD+mzJmiIzo0y3aZjUB69rEI5sam7kNytpOeK/19aGNcPzxDZqg0/h684lScFrcMvt6EBUt/3aJaTab/b4Uho8/fikiq/xNMgpWE2gAAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-15',
      src: { full: '/img/interior/interior-15-full.jpg', card: '/img/interior/interior-15-card.jpg', thumb: '/img/interior/interior-15-thumb.jpg' },
      webp: { full: '/img/interior/interior-15-full.webp', card: '/img/interior/interior-15-card.webp', thumb: '/img/interior/interior-15-thumb.webp' },
      width: 1518,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUABAAPxFysFAsJqSisAgBgCIJQBWABA+ze7fQD1NDIKpAAP3jZHcIojX7iFd9tZlPp4mYbqxucBeJcnvNAut6/hDRAHvN2bTxB/gjQSUTTw/ijUSxEWpORy4MptP+/p95D+AQAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-16',
      src: { full: '/img/interior/interior-16-full.jpg', card: '/img/interior/interior-16-card.jpg', thumb: '/img/interior/interior-16-thumb.jpg' },
      webp: { full: '/img/interior/interior-16-full.webp', card: '/img/interior/interior-16-card.webp', thumb: '/img/interior/interior-16-thumb.webp' },
      width: 1600,
      height: 1159,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoUAA4APxFysFAsJqSisAgBgCIJZQC7AB9OV/mchFe1/LyAAPcyUjJCBy4GCbIb6Xs19D0njf9U1ayNpkt6xhc8ORS1KdNZVAnqYytEppCI2Ra812pSpzpAtLTLp4jYuOJ5uAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-17',
      src: { full: '/img/interior/interior-17-full.jpg', card: '/img/interior/interior-17-card.jpg', thumb: '/img/interior/interior-17-thumb.jpg' },
      webp: { full: '/img/interior/interior-17-full.webp', card: '/img/interior/interior-17-card.webp', thumb: '/img/interior/interior-17-thumb.webp' },
      width: 1600,
      height: 1159,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQAwCdASoUAA4APxFysFAsJqSisAgBgCIJZQC7ABLHCrOvX0tAAP5X8Gro03C82daxR4+Yfxp+XHbkOKEuuo/otIv2gGgBkYdvSjPqWXQ5khzJJG7uiNUm0kJ8hKNL7encC9VxRGICv2VEnbbsGTQs337iuiAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-18',
      src: { full: '/img/interior/interior-18-full.jpg', card: '/img/interior/interior-18-card.jpg', thumb: '/img/interior/interior-18-thumb.jpg' },
      webp: { full: '/img/interior/interior-18-full.webp', card: '/img/interior/interior-18-card.webp', thumb: '/img/interior/interior-18-thumb.webp' },
      width: 1600,
      height: 1174,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAwCdASoUAA8APxFysFAsJqSisAgBgCIJZQAAPMZ1JAe6GAD+3wol4kzfC/iuSn/RpawyRAvtIZUfZay1MRmi8/t3w4vcAZC9+2mrcAmmwCjerpoqKEwu5EcZxY1GNB0eu4SfoOYNalEOhZwAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-19',
      src: { full: '/img/interior/interior-19-full.jpg', card: '/img/interior/interior-19-card.jpg', thumb: '/img/interior/interior-19-thumb.jpg' },
      webp: { full: '/img/interior/interior-19-full.webp', card: '/img/interior/interior-19-card.webp', thumb: '/img/interior/interior-19-thumb.webp' },
      width: 1200,
      height: 800,
      lqip: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwDImCBTEgPEJjJIUZ+YAP5rshfBrROGtvxCpcFYcg5NVOyZ0+7ImY3uCrAFcPvxGXWdmqVOxjTVx/Lr4iaa5x3XWqKxqgAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-20',
      src: { full: '/img/interior/interior-20-full.jpg', card: '/img/interior/interior-20-card.jpg', thumb: '/img/interior/interior-20-thumb.jpg' },
      webp: { full: '/img/interior/interior-20-full.webp', card: '/img/interior/interior-20-card.webp', thumb: '/img/interior/interior-20-thumb.webp' },
      width: 1200,
      height: 849,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwBACdASoUAA4APxFysFAsJqSisAgBgCIJZQC7Ef/gOFaMfKM6lUSCxCAA/sdO5jw83MbAoNkElfDl4M0OSd5P17/7sp1x8GhfIHyBqx2weCd1UOs48+wSn/i7hcKL1jGs88MsVAjLea80VAAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-21',
      src: { full: '/img/interior/interior-21-full.jpg', card: '/img/interior/interior-21-card.jpg', thumb: '/img/interior/interior-21-thumb.jpg' },
      webp: { full: '/img/interior/interior-21-full.webp', card: '/img/interior/interior-21-card.webp', thumb: '/img/interior/interior-21-thumb.webp' },
      width: 1200,
      height: 945,
      lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAwCdASoUABAAPxFysFAsJqSisAgBgCIJZwAAPwW++CGiAAD+lJF0Y1NCU2dRiGGYuLQDrudX+ThAuLWkRnGHGQrXJi/Qo+Bb0CbkMogAZi/J+IgHijhZFzhfu4sdHHpSi6VQcPA4AA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-22',
      src: { full: '/img/interior/interior-22-full.jpg', card: '/img/interior/interior-22-card.jpg', thumb: '/img/interior/interior-22-thumb.jpg' },
      webp: { full: '/img/interior/interior-22-full.webp', card: '/img/interior/interior-22-card.webp', thumb: '/img/interior/interior-22-thumb.webp' },
      width: 1280,
      height: 853,
      lqip: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUAA0APxFysFAsJqSisAgBgCIJQBOg7wAMs4ioTiOOCgSAAP1rI5qmx116Es+E3rI1Msoq+MSJP/eEIWJo++ms8ORnsXIV+sEpXFDgkcTT2oBNkywiaseQydTeAq4gAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-23',
      src: { full: '/img/interior/interior-23-full.jpg', card: '/img/interior/interior-23-card.jpg', thumb: '/img/interior/interior-23-thumb.jpg' },
      webp: { full: '/img/interior/interior-23-full.webp', card: '/img/interior/interior-23-card.webp', thumb: '/img/interior/interior-23-thumb.webp' },
      width: 1050,
      height: 560,
      lqip: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAAsAPxFwsFAsJiSisAgBgCIJZQC2yCB+mP/1dEXxl/AAAPzJdlm5YDcObe3501OZPx3jycATLp/RBSqCLxME3wpwZQLlg9mj54bVTVqJaJUwYcOFbFDTD5KtpC9EPAAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-24',
      src: { full: '/img/interior/interior-24-full.jpg', card: '/img/interior/interior-24-card.jpg', thumb: '/img/interior/interior-24-thumb.jpg' },
      webp: { full: '/img/interior/interior-24-full.webp', card: '/img/interior/interior-24-card.webp', thumb: '/img/interior/interior-24-thumb.webp' },
      width: 1280,
      height: 853,
      lqip: 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAA0APxF0sFCsJqSisAgBgCIJZQCw7CIZeVd350nvLKMAAP3YJJqiRRG+vd4CM3WyPzHAcJkwAqAgBK4nlN0rft5uR11Km2fc1dhQ1D1zE2A3Syb1qnLTAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-25',
      src: { full: '/img/interior/interior-25-full.jpg', card: '/img/interior/interior-25-card.jpg', thumb: '/img/interior/interior-25-thumb.jpg' },
      webp: { full: '/img/interior/interior-25-full.webp', card: '/img/interior/interior-25-card.webp', thumb: '/img/interior/interior-25-thumb.webp' },
      width: 1050,
      height: 560,
      lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAAsAPxFysFAsJqSisAgBgCIJYwCdAA8HkIHnq9zr8AAA/e0BaFlvkTgo/sgoK3uK5nUf3u5TfnGhcUNYtv3/+8pP6xBK5vI10RJwI/lucxIKugAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-26',
      src: { full: '/img/interior/interior-26-full.jpg', card: '/img/interior/interior-26-card.jpg', thumb: '/img/interior/interior-26-thumb.jpg' },
      webp: { full: '/img/interior/interior-26-full.webp', card: '/img/interior/interior-26-card.webp', thumb: '/img/interior/interior-26-thumb.webp' },
      width: 1600,
      height: 1153,
      lqip: 'data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAwCdASoUAA4APxFysFAsJqSisAgBgCIJQAAIELIgO7C+AAD467TKJixBjuGB0KyhyhjKL0rX6DpbFfUC35F2mjNLWFAp7U5ueHEd5aiDwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-27',
      src: { full: '/img/interior/interior-27-full.jpg', card: '/img/interior/interior-27-card.jpg', thumb: '/img/interior/interior-27-thumb.jpg' },
      webp: { full: '/img/interior/interior-27-full.webp', card: '/img/interior/interior-27-card.webp', thumb: '/img/interior/interior-27-thumb.webp' },
      width: 1600,
      height: 1118,
      lqip: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA4APxFysFAsJqSisAgBgCIJYwCw7BW/KUtON5LWwAD+j0mLCOC8HdfMbgf6ohmHyJkIaUiPRgbJ9eI7EXfvnwRHLhEeD7vnAZ0P6sK+yCrftgOLXyUspj1fzlAbVDAYdGILgIAAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-28',
      src: { full: '/img/interior/interior-28-full.jpg', card: '/img/interior/interior-28-card.jpg', thumb: '/img/interior/interior-28-thumb.jpg' },
      webp: { full: '/img/interior/interior-28-full.webp', card: '/img/interior/interior-28-card.webp', thumb: '/img/interior/interior-28-thumb.webp' },
      width: 1600,
      height: 1068,
      lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQAwCdASoUAA0APxFysFAsJqSisAgBgCIJYwC06BbN/41fMLLQAPxk/FvDnJLCQLiWEpHmrwrewAgjCIv26QCGWFpKFhYZtDZBe9eU+XUwQjo/uj5Aa/u8iTqw5iejBbs8MAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-29',
      src: { full: '/img/interior/interior-29-full.jpg', card: '/img/interior/interior-29-card.jpg', thumb: '/img/interior/interior-29-thumb.jpg' },
      webp: { full: '/img/interior/interior-29-full.webp', card: '/img/interior/interior-29-card.webp', thumb: '/img/interior/interior-29-thumb.webp' },
      width: 1600,
      height: 1120,
      lqip: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoUAA4APxFysFAsJqSisAgBgCIJYwCnFB92njYFS2t++7VqAADJMQKUiwsZhZBCx/lVyn59UjAiGQBfgjTmsqFPPk3a5WtTgzANtLo/DYTH45AVQfLOm03I1r5SDNNEAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-30',
      src: { full: '/img/interior/interior-30-full.jpg', card: '/img/interior/interior-30-card.jpg', thumb: '/img/interior/interior-30-thumb.jpg' },
      webp: { full: '/img/interior/interior-30-full.webp', card: '/img/interior/interior-30-card.webp', thumb: '/img/interior/interior-30-thumb.webp' },
      width: 1576,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQBACdASoUAA8APxFysFAsJqSisAgBgCIJZQCw7CPXZ5MQahDibYNyuAD+Z9jI+X8qip4eUMN2wlIY33Wr6Rb++bI9uhThD0l/WD70TYRiK8TSjPeF1mC1AlHAAA==',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-31',
      src: { full: '/img/interior/interior-31-full.jpg', card: '/img/interior/interior-31-card.jpg', thumb: '/img/interior/interior-31-thumb.jpg' },
      webp: { full: '/img/interior/interior-31-full.webp', card: '/img/interior/interior-31-card.webp', thumb: '/img/interior/interior-31-thumb.webp' },
      width: 1552,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoUAA8APxFysFAsJqSisAgBgCIJZQC06B0/Rx8K1InMO/DwAPisMWDLTw5j+gA2+h9xX3/rFmd/VMEDDhQ41i/IuxumJpDczq2Mg83UjITMHv7QdJDRTJNuv8tXEC95EBFHAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-32',
      src: { full: '/img/interior/interior-32-full.jpg', card: '/img/interior/interior-32-card.jpg', thumb: '/img/interior/interior-32-thumb.jpg' },
      webp: { full: '/img/interior/interior-32-full.webp', card: '/img/interior/interior-32-card.webp', thumb: '/img/interior/interior-32-thumb.webp' },
      width: 1415,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoUABEAPxF2slGsJySiqA1RgCIJZQDImBCRut+offrDiF+HRUUKfkAA/sinPWF1v6N2aWR5X536GvO3zlzsiIaWI8g/a7OX5VyspUh6hz0CVp7mddYdeH24RhDiVGUD1wv3GfM4ABODPL9wOMhhLzL02B0Odp0AAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-33',
      src: { full: '/img/interior/interior-33-full.jpg', card: '/img/interior/interior-33-card.jpg', thumb: '/img/interior/interior-33-thumb.jpg' },
      webp: { full: '/img/interior/interior-33-full.webp', card: '/img/interior/interior-33-card.webp', thumb: '/img/interior/interior-33-thumb.webp' },
      width: 1600,
      height: 1138,
      lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoUAA4APxFysFAsJqSisAgBgCIJQBOmUABbdCfN+z5k8AFmAAD+1CzJjSeouxlJ7Xw3YBk6w0JsJSKRr7L2Jc04BBw6hAH3hDmIsRD9taex9PFsXfIOCZzuV58HeAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-34',
      src: { full: '/img/interior/interior-34-full.jpg', card: '/img/interior/interior-34-card.jpg', thumb: '/img/interior/interior-34-thumb.jpg' },
      webp: { full: '/img/interior/interior-34-full.webp', card: '/img/interior/interior-34-card.webp', thumb: '/img/interior/interior-34-thumb.webp' },
      width: 1280,
      height: 853,
      lqip: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoUAA0APxFysVAsJqSisAgBgCIJYwCdACPaCMWY/VTk+Y5iAADeYiE4AtcR3YMC1cqhJbNHW1dbSSu+NUAKLbGyy7DChP6t8x6MArPQHi1SMP08PSxqJGrqr8QzBTf7UtrsXMV5Bw73eQzNN/VWgiQAAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-35',
      src: { full: '/img/interior/interior-35-full.jpg', card: '/img/interior/interior-35-card.jpg', thumb: '/img/interior/interior-35-thumb.jpg' },
      webp: { full: '/img/interior/interior-35-full.webp', card: '/img/interior/interior-35-card.webp', thumb: '/img/interior/interior-35-thumb.webp' },
      width: 1280,
      height: 853,
      lqip: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJZQCdABVf2qx2YIUKMIAAy/vwJMN2tFbze6Vd7jo7eLjLZhPK2f7mJXs08ySfLW0857XMOmAhB583BZiIYT4XFv8gAAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-36',
      src: { full: '/img/interior/interior-36-full.jpg', card: '/img/interior/interior-36-card.jpg', thumb: '/img/interior/interior-36-thumb.jpg' },
      webp: { full: '/img/interior/interior-36-full.webp', card: '/img/interior/interior-36-card.webp', thumb: '/img/interior/interior-36-thumb.webp' },
      width: 1519,
      height: 1200,
      lqip: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUABAAPxFysFAsJqSisAgBgCIJQBOgBAqSwE52UGjFscyAAPiml+mgZ0B+73c+UY8pyMAh4IGvPBO7hPLrso7J5zqytuqRp3R+2OYTfF+NEOFxzsFhWZnVyRKMo1s5AAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-37',
      src: { full: '/img/interior/interior-37-full.jpg', card: '/img/interior/interior-37-card.jpg', thumb: '/img/interior/interior-37-thumb.jpg' },
      webp: { full: '/img/interior/interior-37-full.webp', card: '/img/interior/interior-37-card.webp', thumb: '/img/interior/interior-37-thumb.webp' },
      width: 1600,
      height: 1197,
      lqip: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUAA8APxFysFAsJqSisAgBgCIJQBibBHp+Qy/yafrcNRVwAP7ImAyMWw9HjxTbtPVAf0QBazLJwkM+2+AsbUtk4DCakV/UPaEp1bb9yf6Y+1Lmih/oaQ/vUFTxamG7Kj6l66/yTcBZ/UWQAAA=',
      alt: '', // TODO: write alt
    },
    {
      id: 'interior/interior-38',
      src: { full: '/img/interior/interior-38-full.jpg', card: '/img/interior/interior-38-card.jpg', thumb: '/img/interior/interior-38-thumb.jpg' },
      webp: { full: '/img/interior/interior-38-full.webp', card: '/img/interior/interior-38-card.webp', thumb: '/img/interior/interior-38-thumb.webp' },
      width: 1600,
      height: 1067,
      lqip: 'data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAA0APxFysFAsJqSisAgBgCIJYgDE2CKNQvPC4ktAxWAA/mAFpckceGAmBbx1s4Yu4TSdAiUYjkUA2RruBoVkQRK7e5DGUnWYEOATW6HnG15M35w5nEFHSdwj7N1dQYR/Aox79ux4hrv/A1AAAA==',
      alt: '', // TODO: write alt
    },
  ],
  'offices': [
    {
      id: 'offices/office-01',
      src: { full: '/img/offices/office-01-full.jpg', card: '/img/offices/office-01-card.jpg', thumb: '/img/offices/office-01-thumb.jpg' },
      webp: { full: '/img/offices/office-01-full.webp', card: '/img/offices/office-01-card.webp', thumb: '/img/offices/office-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQC+SywBes2J6zskecIAAP7fn/PyqNQIBFHJ4H29AoI2KdDd9/uLfpRqc2oNZcZ6xZSMn4F4O3jBWOmwRw2WBVVU8ZTfeXKEC2yzNPp8FoWgFSUk9hJZ2eUoMAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'offices/office-02',
      src: { full: '/img/offices/office-02-full.jpg', card: '/img/offices/office-02-card.jpg', thumb: '/img/offices/office-02-thumb.jpg' },
      webp: { full: '/img/offices/office-02-full.webp', card: '/img/offices/office-02-card.webp', thumb: '/img/offices/office-02-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQDG9BDsQaWIckAARwAA++lIncxOGCpItirwb8QnUyZ03/oZQyMp32DvnK41WZ29cFp+TBLEAgh9Dht1vIBAIcOU5xvqC7KsE/Q2PxHenOpJ+BXFxoMY8bfWeB8g6UOQAA==',
      alt: '', // TODO: write alt
    },
  ],
  'services': [
    {
      id: 'services/bedroom-01',
      src: { full: '/img/services/bedroom-01-full.jpg', card: '/img/services/bedroom-01-card.jpg', thumb: '/img/services/bedroom-01-thumb.jpg' },
      webp: { full: '/img/services/bedroom-01-full.webp', card: '/img/services/bedroom-01-card.webp', thumb: '/img/services/bedroom-01-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD3D5/4iIICQgPPB/rW5BRP+TtwQAVlA4IHAAAAAwBACdASoUABAAPxFysFAsJqSisAgBgCIJZwDG9CLt7TiOUpvjyzXU7AAA/sRlflZWISQ1q//Gen951X+Avjjh5JjYhZ3s68ORMBN4UBL43DrkdQIMlEn4FjEe7qMawKDzE+G59s6zPcKgDqAAUlAA',
      alt: '', // TODO: write alt
      roomKind: 'bedroom',
    },
    {
      id: 'services/dining-01',
      src: { full: '/img/services/dining-01-full.jpg', card: '/img/services/dining-01-card.jpg', thumb: '/img/services/dining-01-thumb.jpg' },
      webp: { full: '/img/services/dining-01-full.webp', card: '/img/services/dining-01-card.webp', thumb: '/img/services/dining-01-thumb.webp' },
      width: 1440,
      height: 1120,
      lqip: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJYwCw7AoApxtkrmoMAAD+lC1oje8xPRb4tB7B1aQHCegk8QuVnVfSFO2aFoID5COyb4qU+YSoymhvMeoZZXZEiaeVTbTLMs/o/Hv9ai8pAAAA',
      alt: '', // TODO: write alt
      roomKind: 'dining',
    },
    {
      id: 'services/living-01',
      src: { full: '/img/services/living-01-full.jpg', card: '/img/services/living-01-card.jpg', thumb: '/img/services/living-01-thumb.jpg' },
      webp: { full: '/img/services/living-01-full.webp', card: '/img/services/living-01-card.webp', thumb: '/img/services/living-01-thumb.webp' },
      width: 1440,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRqIAAABXRUJQVlA4WAoAAAAQAAAAEwAADwAAQUxQSBUAAAARD/D4/4iIICQgPPB/rW5BRP+TtwQAVlA4IGYAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJYwCsABmOfzHRRcRW6AD3rHgySz2h2wSo1qxUDx0B6+9BhhbZTreaDoJV6MUvRjWSW5798k/ZgN68Q8bZXbSwAOL961SrAebPs9VcAAA=',
      alt: '', // TODO: write alt
      roomKind: 'living',
    },
    {
      id: 'services/meeting-01',
      src: { full: '/img/services/meeting-01-full.jpg', card: '/img/services/meeting-01-card.jpg', thumb: '/img/services/meeting-01-thumb.jpg' },
      webp: { full: '/img/services/meeting-01-full.webp', card: '/img/services/meeting-01-card.webp', thumb: '/img/services/meeting-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJZQDG9BL8UKUxUC1VcAD76UidzE4YR+Uk3KNFD50Y7UZV0hFGL8LbfcVDnYcWR8jC6Oygd/3fC/bgFYYbc6nBPrm3P0S971TBlkuHC9OGn4O6AI2oEjstku27PrkHzqwKwAAA',
      alt: '', // TODO: write alt
    },
    {
      id: 'services/villa-01',
      src: { full: '/img/services/villa-01-full.jpg', card: '/img/services/villa-01-card.jpg', thumb: '/img/services/villa-01-thumb.jpg' },
      webp: { full: '/img/services/villa-01-full.webp', card: '/img/services/villa-01-card.webp', thumb: '/img/services/villa-01-thumb.webp' },
      width: 1441,
      height: 1121,
      lqip: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACwAwCdASoUABAAPxFysFAsJqSisAgBgCIJQAAKp/E0HBCpNL+5YAD90k26p8ULhV6D+tXWB6PM1QicjZvEwwpEet5Venu705YFX1u4kWH6ce649iijAJHeSYC4Vx+vEvnBQjww4VeGxLc7HieaIoJSYMeiHROaEHVlFQAA',
      alt: '', // TODO: write alt
    },
  ],
};
